export default {
  GET_DEALER_TOOLS_START: 'dealerTools/get_dealer_tools_start',
  GET_DEALER_TOOLS_REQUEST: 'dealerTools/get_dealer_tools_request',
  GET_DEALER_TOOLS_SUCCESS: 'dealerTools/get_dealer_tools_success',
  EMPTY_DEALER_TOOLS_REQUEST: 'dealerTools/empty_dealer_tools_request',
  DEALER_TOOLS_ERROR: 'dealerTools/dealer_tools_error',

  GET_LTP_START: 'ltp/get_ltp_start',
  GET_LTP_REQUEST: 'ltp/get_ltp_request',
  GET_LTP_SUCCESS: 'ltp/get_ltp_success',
  EMPTY_LTP_REQUEST: 'ltp/empty_ltp_request',
  LTP_ERROR: 'ltp/ltp_error',

  GET_NEWS_START: 'news/get_news_start',
  GET_NEWS_REQUEST: 'news/get_news_request',
  GET_NEWS_SUCCESS: 'news/get_news_success',
  INCREMENT_NEWS_VIEW_COUNT: 'odis/incrementNewsViewCount',
  RESET_NEWS_VIEW_COUNT: 'odis/resetNewsViewCount',
  NEWS_ERROR: 'news/news_error',

  GET_ODIS_START: 'odis/get_odis_start',
  GET_ODIS_REQUEST: 'odis/get_odis_request',
  GET_ODIS_SUCCESS: 'odis/get_odis_success',
  INCREMENT_ODIS_VIEW_COUNT: 'odis/incrementOdisViewCount',
  RESET_ODIS_VIEW_COUNT: 'odis/resetOdisViewCount',
  ODIS_ERROR: 'odis/odis_error',

  GET_PRODUCTS_START: 'products/get_products_start',
  GET_PRODUCTS_REQUEST: 'products/get_products_request',
  GET_PRODUCTS_SUCCESS: 'products/get_products_success',
  INCREMENT_PRODUCTS_VIEW_COUNT: 'odis/incrementProductsViewCount',
  RESET_PRODUCTS_VIEW_COUNT: 'odis/resetProductsViewCount',
  PRODUCTS_ERROR: 'products/products_error',

  GET_STATS_START: 'stats/get_stats_start',
  GET_STATS_REQUEST: 'stats/get_stats_request',
  GET_STATS_SUCCESS: 'stats/get_stats_success',
  STATS_ERROR: 'stats/stats_error',

  GET_USER_START: 'user/get_user_start',
  GET_USER_REQUEST: 'user/get_user_request',
  GET_USER_RESET_ERRORS: 'user/get_user_reset_errors',
  GET_USER_SUCCESS: 'user/get_user_success',
  SIGN_OUT_USER_REQUEST: 'user/sign_out_user',
  GET_USER_INVALID_CREDS: 'user/get_user_invalid_credentials',
  USER_ERROR: 'user/user_error',

  GET_USERS_START: 'users/get_users_start',
  GET_USERS_REQUEST: 'users/get_users_request',
  GET_USERS_SUCCESS: 'users/get_users_success',
  DELETE_USER_REQUEST: 'users/delete_user_request',
  CREATE_USER_REQUEST: 'users/create_user_request',
  USERS_ERROR: 'users/user_error',

  GET_DEALER_WIPS_START: 'dealerWips/get_dealer_wips_start',
  GET_DEALER_WIPS: 'dealerWips/get_dealer_wips_start',
  GET_DEALER_WIPS_REQUEST: 'dealerWips/get_dealer_wips_request',
  GET_DEALER_WIPS_SUCCESS: 'dealerWips/get_dealer_wips_success',
  DELETE_DEALER_WIP_TOOL_REQUEST: 'dealerWips/delete_dealer_wip_tool_request',
  DELETE_DEALER_WIP_TOOL_SUCCESS: 'dealerWips/delete_dealer_wip_tool_success',
  DELETE_DEALER_WIP_REQUEST: 'dealerWips/delete_dealer_wip_request',
  DELETE_DEALER_WIP_SUCCESS: 'dealerWips/delete_dealer_wip_success',
  CREATE_DEALER_WIP_START: 'dealerWips/create_dealer_wip_start',
  CREATE_DEALER_WIP_REQUEST: 'dealerWips/create_dealer_wip_request',
  DEALER_WIP_UNAVAILABLE_TOOLS: 'dealerWips/DEALER_WIP_UNAVAILABLE_TOOLS',
  CREATE_DEALER_WIP_SUCCESS: 'dealerWips/create_dealer_wip_success',
  EMPTY_DEALER_WIPS_REQUEST: 'dealerWips/empty_dealer_wips_request',
  DEALER_WIPS_ERROR: 'dealerWips/dealer_wips_error',

  FORM_INPUT_UPDATE: 'FORM_INPUT_UPDATE'
};
