const constants = {
  addListener: [Functionanonymous],
  appOwnership: 'expo',
  debugMode: false,
  deviceName: 'iPhone 12 Pro',
  executionEnvironment: 'storeClient',
  experienceUrl: 'exp://192.168.1.112:19000',
  expoConfig: {
    _internal: {
      dynamicConfigPath: [Object],
      isDebug: false,
      packageJsonPath:
        '/Users/aupstone/ProjectsOnBigMac/PocketInfoweb/PocketInfowebPro/PocketInfowebReactNative SDK 47/package.json',
      pluginHistory: [Object],
      projectRoot:
        '/Users/aupstone/ProjectsOnBigMac/PocketInfoweb/PocketInfowebPro/PocketInfowebReactNative SDK 47',
      staticConfigPath:
        '/Users/aupstone/ProjectsOnBigMac/PocketInfoweb/PocketInfowebPro/PocketInfowebReactNative SDK 47/app.json',
    },
    android: {
      googleServicesFile:
        '{   "project_info": {     "project_number": "404368859327",     "firebase_url": "https://vwguk-pocketinfoweb.firebaseio.com",     "project_id": "vwguk-pocketinfoweb",     "storage_bucket": "vwguk-pocketinfoweb.appspot.com"   },   "client": [     {       "client_info": {         "mobilesdk_app_id": "1:404368859327:android:c7e5227112ac4643b8660a",         "android_client_info": {           "package_name": "com.helpfulconsultants.pocketinfowebpro"         }       },       "oauth_client": [         {           "client_id": "404368859327-g5juf4v4vu9fmudifgfohhfotg521uog.apps.googleusercontent.com",           "client_type": 3         }       ],       "api_key": [         {           "current_key": "AIzaSyBgtHndV2CGhSbOhy64yJTIKvII73lT4L8"         }       ],       "services": {         "appinvite_service": {           "other_platform_oauth_client": [             {               "client_id": "404368859327-g5juf4v4vu9fmudifgfohhfotg521uog.apps.googleusercontent.com",               "client_type": 3             }           ]         }       }     }   ],   "configuration_version": "1" } ',
      package: 'com.helpfulconsultants.pocketinfowebpro',
      permissions: [Array],
      runtimeVersion: [Object],
      versionCode: 30,
    },
    androidNavigationBar: {
      backgroundColor: '#3689b1',
      barStyle: 'light-content',
    },
    androidStatusBar: {
      backgroundColor: '#0b4a76',
      barStyle: 'light-content',
    },
    assetBundlePatterns: ['assets/images/*', 'assets/fonts/*'],
    description: 'Find your tools inventory.',
    extra: {
      eas: [Object],
    },
    hooks: {
      postPublish: [Array],
    },
    hostUri: '192.168.1.112:19000',
    icon: './assets/images/icon.png',
    iconUrl: 'http://192.168.1.112:19000/assets/./assets/images/icon.png',
    ios: {
      buildNumber: '124',
      bundleIdentifier: 'com.helpfulconsultants.pocketinfowebpro',
      infoPlist: [Object],
      supportsTablet: true,
    },
    name: 'Pocket Infoweb',
    orientation: 'portrait',
    platforms: ['ios', 'android'],
    plugins: ['sentry-expo'],
    privacy: 'public',
    sdkVersion: '47.0.0',
    slug: 'PocketInfoweb-Dev',
    splash: {
      backgroundColor: '#ffffff',
      image: './assets/images/splash.png',
      imageUrl: 'http://192.168.1.112:19000/assets/./assets/images/splash.png',
      resizeMode: 'contain',
    },
    updates: {
      checkAutomatically: 'ON_ERROR_RECOVERY',
      enabled: true,
      fallbackToCacheTimeout: 0,
      url: 'https://u.expo.dev/0a540561-d833-425b-8955-13bf1915cc35',
    },
    version: '1.2.72',
  },
  expoRuntimeVersion: '2.26.4.101',
  expoVersion: '2.26.4.101',
  getWebViewUserAgentAsync: [Functionanonymous],
  isDetached: false,
  isDevice: false,
  isHeadless: false,
  linkingUri: 'exp://192.168.1.112:19000/',
  manifest: null,
  manifest2: {
    assets: [],
    createdAt: '2023-06-19T11:05:12.600Z',
    extra: {
      eas: [Object],
      expoClient: [Object],
      expoGo: [Object],
      scopeKey: '@alan-upstone/PocketInfoweb-Dev',
    },
    id: '0a18f9d4-7913-48ce-8da8-d090f1996dd6',
    isVerified: true,
    launchAsset: {
      contentType: 'application/javascript',
      key: 'bundle',
      url: 'http://192.168.1.112:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false',
    },
    metadata: {},
    runtimeVersion: 'exposdk:47.0.0',
  },
  nativeAppVersion: '2.26.4',
  nativeBuildVersion: '2.26.4.101',
  platform: {
    ios: {
      buildNumber: null,
      platform: 'x86_64',
      systemVersion: '15.2',
      userInterfaceIdiom: 'handset',
    },
  },
  removeListeners: [Functionanonymous],
  sessionId: '38ABDCCF-A63C-425B-B1C6-27CC0A892E61',
  statusBarHeight: 47,
  supportedExpoSdks: ['45.0.0', '46.0.0', '47.0.0'],
  systemFonts: ['Zapfino'],
};
