export default serviceMeasuresDummyData = [
  {
    id: '250',
    menuText: 'Electronic measuring system for camshaft adjustment ',
    toolsAffected: 'VAS 611 007',
    toolBrief: 'Service measure _VAS 611007_.pdf',
    dateCreated: '06/12/2019 15:16:00',
    lastUpdated: '12/02/2020 13:53:47',
    updatedBy: 'Lyndon Evans',
    expiryDate: '26/02/2020',
    startDate: '16/12/2019',
    actionSteps: 'YYNNYNNN',
    actionText:
      'Please mark this Service Measure as Completed ONLY WHEN you have carried out the conversion with the kit provided.',
    auTargetSites: '133',
    vwTargetSites: '235',
    seTargetSites: '139',
    skTargetSites: '150',
    cvTargetSites: '100',
    auTargetItems: '133',
    vwTargetItems: '235',
    seTargetItems: '139',
    skTargetItems: '150',
    cvTargetItems: '100',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'STEP 1.  Is the serial number of your VAS 611007 within the affected range as outlined in the adjacent service brief i.e.  lower than 02500?',
    confirmationQuestion:
      'STEP 3 Please mark this Service Measure as Completed by *** the kit provided. Then select the green button below, Confirm all actions have been completed. \r\n',
    serialNumberQuestion:
      'STEP 2.  Please provide the Serial Number for your VAS 611007 in the field below . Once we receive this, we will send a Conversion Kit to you in your parts cage. At this stage please save your progress by clicking the yellow Save Progress button below',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '',
  },
  {
    id: '253',
    menuText:
      'T40093/5 Service Measure Part One:  part of engine support bracket',
    toolsAffected: 'T40093/5 bracket',
    toolBrief: 'Service Measure _T40093-5_2020-05_eng.pdf',
    dateCreated: '09/06/2020 11:45:58',
    lastUpdated: '16/07/2020 16:55:53',
    updatedBy: 'Lyndon Evans',
    expiryDate: '15/07/2020',
    startDate: '09/06/2020',
    actionSteps: 'NNNNNNNN',
    actionText: '',
    auTargetSites: '136',
    vwTargetSites: '220',
    seTargetSites: '140',
    skTargetSites: '152',
    cvTargetSites: '100',
    auTargetItems: '136',
    vwTargetItems: '220',
    seTargetItems: '140',
    skTargetItems: '152',
    cvTargetItems: '100',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'Do you have a affected T40093/5 as per the image and briefing details attached. i.e does your T40093/5 have an additional weld as per the image?',
    confirmationQuestion:
      'Have you completed all actions for the service measure?',
    serialNumberQuestion: 'Please provide a serial number for the item.',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '',
  },
  {
    id: '256',
    menuText: 'Recall of adapters T40093/6 and T40150/8: Phase One',
    toolsAffected: 'T40093/6 and T40150/8',
    toolBrief: 'Service Measure Recall T40093-6 and T40150-8.pdf',
    dateCreated: '28/10/2020 12:50:45',
    lastUpdated: '29/10/2020 16:38:34',
    updatedBy: 'Beth Clarke',
    expiryDate: '13/11/2020',
    startDate: '30/10/2020',
    actionSteps: 'YYNNNNNY',
    actionText:
      'We will confirm in a 2nd phase Service Measure how we will exchange all identified items.',
    auTargetSites: '136',
    vwTargetSites: '249',
    seTargetSites: '145',
    skTargetSites: '155',
    cvTargetSites: '103',
    auTargetItems: '136',
    vwTargetItems: '249',
    seTargetItems: '145',
    skTargetItems: '155',
    cvTargetItems: '103',
    numItemsText:
      'How many affected items (T40093/6 or T40150/8) combined  do you have and/or have you sold?',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      "Are the tools T40093/6, sold as part of T40093, T40093A and T40093B or T40150/8 sold as part of T40150 in your workshop or have you sold any of them to 3rd parties? \r\nIf yes,  remove them from your workshop and clearly mark them as 'NOT FIT FOR USE'\r\n",
    confirmationQuestion:
      'Have you quarantined all of the reported affected equipment?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '',
  },
  {
    id: '259',
    menuText: 'T10254/5  PHASE ONE',
    toolsAffected: 'T10254, T10254/5, V03839037M and V03839310BD',
    toolBrief: 'T10254-5.pdf',
    dateCreated: '13/11/2020 09:02:50',
    lastUpdated: '13/11/2020 09:06:01',
    updatedBy: 'Simon Groves',
    expiryDate: '27/11/2020',
    startDate: '14/11/2020',
    actionSteps: 'YNNNNNNY',
    actionText: '',
    auTargetSites: '136',
    vwTargetSites: '249',
    seTargetSites: '145',
    skTargetSites: '155',
    cvTargetSites: '103',
    auTargetItems: '136',
    vwTargetItems: '249',
    seTargetItems: '155',
    skTargetItems: '145',
    cvTargetItems: '103',
    numItemsText:
      'How many affected items (T10254/5) do you have and/or have you sold?',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      "Is the component T10254/5 (which has been sold as part of the kits or via an individual part number T10254, T10254/5, V03839037M and V03839310BD)  in your workshop or have you sold any of them to 3rd parties? \r\nIf yes,  remove them from your workshop and clearly mark them as 'NOT FIT FOR USE'\r\n",
    confirmationQuestion:
      'Have you quarantined all of the reported affected equipment?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '',
  },
  {
    id: '260',
    menuText: 'T10057 Release Tool',
    toolsAffected: 'T10057 Release Tool belonging to Production Batch G10',
    toolBrief: 'T10057_2020_12_eng-2.pdf',
    dateCreated: '22/12/2020 15:49:24',
    lastUpdated: '08/01/2021 11:51:42',
    updatedBy: 'Simon Groves',
    expiryDate: '29/01/2021',
    startDate: '08/01/2021',
    actionSteps: 'YYNNNNNY',
    actionText:
      'You MUST return the faulty T10057 via returns code type ZRU0: item category is ZH1.  But only after your order for a replacement is received. This will then create a credit note for your new order.',
    auTargetSites: '130',
    vwTargetSites: '212',
    seTargetSites: '133',
    skTargetSites: '145',
    cvTargetSites: '96',
    auTargetItems: '130',
    vwTargetItems: '213',
    seTargetItems: '133',
    skTargetItems: '145',
    cvTargetItems: '96',
    numItemsText: 'Please report the number of affected items in your workshop',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'Please check your T10057 release tools from Production Batch G10 (images 1 and 2) delivered from March 2019 onwards. Do they belong to batch G10?',
    confirmationQuestion:
      'Please confirm you have read and understand the actions you are required to take in this Quality Measure.',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '2',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '',
  },
];
