export default ltpLoansDummyData = [
  {
    VIN: 'WVWZZZ1EW12154215',
    adminBy: '',
    adminText: '',
    adminUpdated: '',
    bookingType: 'hard',
    ccamBy: '',
    ccamDate: '',
    ccamNumber: '',
    chargeComment: '',
    chargeDate: '',
    chargeStatus: '',
    chargeValue: '',
    collectedBy: '',
    collectedDate: '',
    collectionNumber: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdBy: 'Lyndon Evans',
    createdDate: '15/04/2021 08:49:54',
    dealerContacts_id: '513',
    dealerRateComment: '',
    dealerRating: '',
    dealers_id: '21000193',
    despatchBy: 'Regan Duggan',
    despatchRef: 'B802209',
    despatchUpdated: '13/04/2021 17:35:01',
    endDateActual: '',
    endDateDue: '26/07/2022',
    extendedBy: '',
    extendedFrom: '',
    extendedOn: '',
    id: '9825',
    loanToolNo: 'LT0210',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    rcptCondition: '',
    receivedBy: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    sapOrderNumber: '36115996',
    sapOrderNumberBy: '',
    sapOrderNumberDate: '13/04/2021 17:13:25',
    sapOrderRequestBy: 'Lyndon Evans',
    sapOrderRequestTime: '13/04/2021 08:50:13',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    startDate: '28/06/2021',
    toolDescription: 'ID3 test leads set',
    tools_id: '567',
    tscBookedBy: '',
    tscBookedDate: '',
  },
  {
    loanToolNo: 'LT0065',
    toolDescription: 'KUKKO 2 set',
    id: '9747',
    dealers_id: '21000005',
    bookingType: 'hard',
    tools_id: '293',
    dealerContacts_id: '903',
    startDate: '10/10/2021',
    endDateDue: '06/11/2021',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '05/10/2021 13:30:14',
    createdBy: 'Charles Browne',
    sapOrderNumber: '35906283',
    sapOrderNumberDate: '19/03/2021 14:35:40',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '19/03/2021 14:27:52',
    sapOrderRequestBy: 'Regan Duggan',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '',
    ccamNumber: '',
    ccamBy: '',
    collectedDate: '',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'B780844',
    despatchBy: 'Regan Duggan',
    despatchUpdated: '19/03/2021 16:31:26',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: 'WV1ZZZSYZJ9040969',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
  },
  {
    loanToolNo: 'LT0001',
    toolDescription: 'Brake servo tester',
    id: '9148',
    dealers_id: '21000005',
    bookingType: 'hard',
    tools_id: '293',
    dealerContacts_id: '903',
    startDate: '02/10/2021',
    endDateDue: '05/11/2021',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '18/03/2021 13:30:14',
    createdBy: 'Charles Browne',
    sapOrderNumber: '35906283',
    sapOrderNumberDate: '19/03/2021 14:35:40',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '19/03/2021 14:27:52',
    sapOrderRequestBy: 'Regan Duggan',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '',
    ccamNumber: '',
    ccamBy: '',
    collectedDate: '',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'B780844',
    despatchBy: 'Regan Duggan',
    despatchUpdated: '19/03/2021 16:31:26',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: 'WV1ZZZSYZJ9040969',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
  },
  {
    loanToolNo: 'LT0007',
    toolDescription: 'Collected tool',
    id: '9748',
    dealers_id: '21000005',
    bookingType: 'hard',
    tools_id: '293',
    dealerContacts_id: '903',
    startDate: '14/10/2021',
    endDateDue: '03/11/2021',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '18/03/2021 13:30:14',
    createdBy: 'Charles Browne',
    sapOrderNumber: '35906283',
    sapOrderNumberDate: '19/03/2021 14:35:40',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '19/03/2021 14:27:52',
    sapOrderRequestBy: 'Regan Duggan',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '',
    ccamNumber: '',
    ccamBy: '',
    collectedDate: '09/10/2021 16:31:26',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'B780844',
    despatchBy: 'Regan Duggan',
    despatchUpdated: '19/03/2021 16:31:26',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: 'WV1ZZZSYZJ9040969',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
  },
  {
    loanToolNo: 'LT0014',
    toolDescription: 'Adjustable support',
    id: '9648',
    dealers_id: '21000005',
    bookingType: 'hard',
    tools_id: '293',
    dealerContacts_id: '903',
    startDate: '20/07/2021',
    endDateDue: '04/11/2021',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '18/03/2021 13:30:14',
    createdBy: 'Charles Browne',
    sapOrderNumber: '35906283',
    sapOrderNumberDate: '19/03/2021 14:35:40',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '19/03/2021 14:27:52',
    sapOrderRequestBy: 'Regan Duggan',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '',
    ccamNumber: '',
    ccamBy: '',
    collectedDate: '',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'B780844',
    despatchBy: 'Regan Duggan',
    despatchUpdated: '19/03/2021 16:31:26',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: 'WV1ZZZSYZJ9040969',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
  },
  {
    VIN: 'WVWZZZ1EW12154215',
    adminBy: '',
    adminText: '',
    adminUpdated: '',
    bookingType: 'hard',
    ccamBy: '',
    ccamDate: '',
    ccamNumber: '',
    chargeComment: '',
    chargeDate: '',
    chargeStatus: '',
    chargeValue: '',
    collectedBy: '',
    collectedDate: '',
    collectionNumber: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdBy: 'Lyndon Evans',
    createdDate: '13/04/2021 08:49:54',
    dealerContacts_id: '513',
    dealerRateComment: '',
    dealerRating: '',
    dealers_id: '21000193',
    despatchBy: 'Regan Duggan',
    despatchRef: 'B802209',
    despatchUpdated: '13/04/2021 17:35:01',
    endDateActual: '',
    endDateDue: '07/11/2021',
    extendedBy: '',
    extendedFrom: '',
    extendedOn: '',
    id: '9825',
    loanToolNo: 'LT0233',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    rcptCondition: '',
    receivedBy: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    sapOrderNumber: '36115996',
    sapOrderNumberBy: '',
    sapOrderNumberDate: '13/04/2021 17:13:25',
    sapOrderRequestBy: 'Lyndon Evans',
    sapOrderRequestTime: '13/04/2021 08:50:13',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    startDate: '28/06/2021',
    toolDescription: 'ID5 test leads set',
    tools_id: '567',
    tscBookedBy: '',
    tscBookedDate: '',
  },
];
