export default ltpLoansDummyData = [
  {
    loanToolNo: 'LT0091',
    toolDescription: 'Fuel Return System Tester',
    id: '17940',
    dealers_id: '21000508',
    bookingType: 'hard',
    tools_id: '242',
    dealerContacts_id: '2943',
    startDate: '11/10/2024',
    endDateDue: '22/10/2024',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '09/10/2024 08:08:30',
    createdBy: 'Jake Wilkinson',
    sapOrderNumber: '47627304 ',
    sapOrderNumberDate: '10/10/2024 06:47:30',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '10/10/2024 05:20:14',
    sapOrderRequestBy: 'Andrew Deville',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '12/10/2024 10:38:36',
    ccamNumber: '63822128',
    ccamBy: 'Jake Wilkinson',
    collectedDate: '',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'E036305',
    despatchBy: 'Thomas Hallam',
    despatchUpdated: '10/10/2024 16:52:33',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: '',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
    useByDate: '16/10/2024',
    lateDespatchReason: '',
  },
  {
    loanToolNo: 'LT0284',
    toolDescription: 'Pressure & Vacuum Pump',
    id: '17941',
    dealers_id: '21000508',
    bookingType: 'hard',
    tools_id: '867',
    dealerContacts_id: '2943',
    startDate: '11/10/2024',
    endDateDue: '22/10/2024',
    endDateActual: '',
    receivedBy: '',
    rcptCondition: '',
    conditionComment: '',
    conditionMgrComment: '',
    createdDate: '09/10/2024 08:08:54',
    createdBy: 'Jake Wilkinson',
    sapOrderNumber: '47627312 ',
    sapOrderNumberDate: '10/10/2024 06:49:05',
    sapOrderNumberBy: '',
    sapOrderRequestTime: '10/10/2024 05:21:00',
    sapOrderRequestBy: 'Andrew Deville',
    dealerRating: '',
    dealerRateComment: '',
    ratedBy: '',
    ratedDate: '',
    ratedIP: '',
    chargeStatus: '',
    chargeComment: '',
    chargeValue: '',
    chargeDate: '',
    sapReceiptDate: '',
    sapReceiptNumber: '',
    ccamDate: '12/10/2024 10:38:31',
    ccamNumber: '63822128',
    ccamBy: 'Jake Wilkinson',
    collectedDate: '',
    collectedBy: '',
    collectionNumber: '',
    despatchRef: 'E036305',
    despatchBy: 'Thomas Hallam',
    despatchUpdated: '10/10/2024 16:52:39',
    adminText: '',
    adminBy: '',
    adminUpdated: '',
    rpuAccessDate: '',
    rpuAccessDateUpdated: '',
    VIN: '',
    penaltyNotifiedBy: '',
    penaltyNotifiedDate: '',
    tscBookedBy: '',
    tscBookedDate: '',
    extendedFrom: '',
    extendedOn: '',
    extendedBy: '',
    useByDate: '16/10/2024',
    lateDespatchReason: '',
  },
];
