export default newsDummyData = [
  {
    id: '88',
    newsType: 'News',
    headline: 'Story:The New VAS 6150F Diagnostic Laptop',
    newstext:
      'The New VAS 6150F diagnosis unit impresses not only due to improved performance, but also due to maximum user safety, extremely high user comfort and numerous other highlights which are ideal for harsh everyday usage in the workshop. In addition, it has been optimally coordinated with the Offboard Diagnostic Information System and the diagnostic interface. A generation that is setting benchmarks.',
    imageName: 'VAS6150F.png',
    linkTo: '?controller=Stories&action=View&id=72',
    createdDate: '28/01/2022 10:30:28',
    lastUpdated: '07/02/2022 18:56:16',
    updatedBy: 'Simon Groves',
    ipAddress: '109.149.144.89',
    businessCritical: 'Y',
    topLine: 'Y',
  },
  {
    id: '99',
    newsType: 'News',
    headline: 'PDF: Straight to the brochure',
    newstext:
      'The New VAS 6150F diagnosis unit impresses not only due to improved performance, but also due to maximum user safety, extremely high user comfort and numerous other highlights which are ideal for harsh everyday usage in the workshop. In addition, it has been optimally coordinated with the Offboard Diagnostic Information System and the diagnostic interface. A generation that is setting benchmarks.',
    imageName: 'VAS6150F.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/Sales_Support/Brochure_VAS6150F.pdf',
    createdDate: '28/01/2022 10:30:28',
    lastUpdated: '07/02/2022 18:56:16',
    updatedBy: 'Simon Groves',
    ipAddress: '109.149.144.89',
    businessCritical: 'Y',
    topLine: 'Y',
  },
  {
    id: '33',
    newsType: 'News',
    headline: 'PDF: The New VAS 6150F Diagnostic Laptop',
    newstext:
      'The New VAS 6150F diagnosis unit impresses not only due to improved performance, but also due to maximum user safety, extremely high user comfort and numerous other highlights which are ideal for harsh everyday usage in the workshop. In addition, it has been optimally coordinated with the Offboard Diagnostic Information System and the diagnostic interface. A generation that is setting benchmarks.',
    imageName: 'VAS6150F.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/Sales_Support/View_The_VAS_6150F_diagnostic_laptop.pdf',
    createdDate: '28/01/2022 10:30:28',
    lastUpdated: '07/02/2022 18:56:16',
    updatedBy: 'Simon Groves',
    ipAddress: '109.149.144.89',
    businessCritical: 'Y',
    topLine: 'Y',
  },
  {
    id: '63',
    newsType: 'News',
    headline: 'PDF: Landscape brochure test',
    newstext:
      'The New VAS 6150F diagnosis unit impresses not only due to improved performance, but also due to maximum user safety, extremely high user comfort and numerous other highlights which are ideal for harsh everyday usage in the workshop. In addition, it has been optimally coordinated with the Offboard Diagnostic Information System and the diagnostic interface. A generation that is setting benchmarks.',
    imageName: 'VAS6150F.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/Sales_Support/landscape_brochure_1.pdf',
    createdDate: '28/01/2022 10:30:28',
    lastUpdated: '07/02/2022 18:56:16',
    updatedBy: 'Simon Groves',
    ipAddress: '109.149.144.89',
    businessCritical: 'Y',
    topLine: 'Y',
  },
  {
    id: '45',
    newsType: 'News',
    headline: 'Further supply shortages VAS 6154A',
    newstext:
      'Updated! Delays in production still affecting the supply chain. As you are no doubt aware from current news reports, many industries are currently experiencing supply bottlenecks regarding electronic components. Unfortunately, the automotive industry is no exception, and the situation impacts not only vehicle \nproduction but workshop equipment and operations as well.',
    imageName: 'chipShortage.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/VAS_Hardware_Support/VAS_6154A/VAS_6154A_Supply_Delays_2021.pdf',
    createdDate: '26/03/2021 10:30:34',
    lastUpdated: '03/02/2022 10:12:03',
    updatedBy: 'Simon Groves',
    ipAddress: '109.149.144.89',
    businessCritical: 'Y',
    topLine: 'Y',
  },
  {
    id: '41',
    newsType: 'News',
    headline: 'Calibration Schedule Updated to Version 18.1',
    newstext:
      'A new version of the Calibration Schedule for Tools & Equipment will be posted on Friday 28th January. This new version replaces all previous versions. Lookout for the TEXT in Red',
    imageName: 'redCarManCalibration.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/10.01.2022_Schedule_and_Tolerances_V18.1.pdf',
    createdDate: '24/11/2020 11:41:14',
    lastUpdated: '28/01/2022 09:42:32',
    updatedBy: 'Simon Groves',
    ipAddress: '31.48.180.31',
    businessCritical: 'N',
    topLine: 'Y',
  },
  {
    id: '10',
    newsType: 'News',
    headline: 'VAS 6154(A) Post Warranty Support',
    newstext:
      'Please view the above document if you have either a damaged device(s) that falls outside of warranty repair, or your devices(s) are out of their warranty period.\nThere are repair costs included in the document on the final page.',
    imageName: '6154-a.PNG',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/VAS_Hardware_Support/VAS_6154A/VAS_6154_Order_for_Repair_with_Costs.pdf',
    createdDate: '08/11/2018 13:37:36',
    lastUpdated: '12/01/2022 11:15:00',
    updatedBy: 'Lyndon Evans',
    ipAddress: '147.161.171.80',
    businessCritical: 'N',
    topLine: 'Y',
  },
  {
    id: '24',
    newsType: 'News',
    headline: 'VAS6154(A) Aftersales Support',
    newstext:
      'Please click the image to view this guide which includes both troubleshooting points for well-known contact points. You will also find contact information for pairing and aftersales support with devices VAS6154 & VAS6154A, still within their Warranty period.',
    imageName: '6154-a.PNG',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/VAS_Hardware_Support/VAS_6154A/VAS6154%20Aftersales%20Support%20September%202020.pdf',
    createdDate: '12/07/2019 10:18:12',
    lastUpdated: '12/01/2022 11:15:23',
    updatedBy: 'Lyndon Evans',
    ipAddress: '147.161.171.80',
    businessCritical: 'N',
    topLine: 'N',
  },
  {
    id: '54',
    newsType: 'News',
    headline: 'Festive Greetings',
    newstext:
      'Festive Greetings and a Happy New Year from Pro-Align.\n\nVAS 6560 and VAS 6533A: treat your workshop to an approved tyre bay package for a special seasonal price!',
    imageName: 'proAlignHeadline.png',
    linkTo: '?controller=Stories&action=View&id=71',
    createdDate: '01/10/2021 11:11:24',
    lastUpdated: '14/12/2021 16:35:21',
    updatedBy: 'Lyndon Evans',
    ipAddress: '109.149.144.36',
    businessCritical: 'N',
    topLine: 'N',
  },
  {
    id: '61',
    newsType: 'News',
    headline: 'A/C Service Unit VAS 581 009 (R744)',
    newstext:
      'With the tried and tested air conditioning service unit VAS 581 009, you will be optimally equipped for the future. An increasing number of our new electric vehicle models are fitted with a CO2 air conditioning system which, when combined with the optional heat pump, reduces energy consumption. Why CO2 is the preferred coolant and how the VAS 581 009 will make the air conditioning service simpler and safer can be seen in the product video.',
    imageName: 'VAS581009.png',
    linkTo:
      'https://toolsinfoweb.co.uk/content/documents/videos/21_11_04_en_WE_Klimaservicegeraet_VAS_581009_720.mp4',
    createdDate: '03/12/2021 19:02:08',
    lastUpdated: '06/12/2021 09:00:12',
    updatedBy: 'Lyndon Evans',
    ipAddress: '165.225.17.169',
    businessCritical: 'N',
    topLine: 'N',
  },
  {
    id: '47',
    newsType: 'News',
    headline: 'Increased Bottleneck Management for Equipment',
    newstext:
      'Sometimes we encounter issues in maintaining sufficient stock to fulfil all of our tools & equipment orders. The reasons are usually outside our control. You can find an update on the current back order position here.',
    imageName: 'viewInsideAWarehouse.png',
    linkTo: '?controller=Stories&action=View&id=38',
    createdDate: '08/04/2021 11:19:57',
    lastUpdated: '24/11/2021 09:37:54',
    updatedBy: 'Simon Groves',
    ipAddress: '165.225.17.177',
    businessCritical: 'N',
    topLine: 'N',
  },
  {
    businessCritical: 'N',
    createdDate: '08/11/2018 13:37:36',
    headline: 'VAS 6154(A) Post Warranty Support',
    id: '10',
    imageName: '6154-a.PNG',
    ipAddress: '147.161.171.80',
    lastUpdated: '12/01/2022 11:15:00',
    linkTo:
      '/content/documents/VAS_Hardware_Support/VAS_6154A/VAS_6154_Order_for_Repair_with_Costs.pdf',
    newsType: 'News',
    newstext:
      'Please view the above document if you have either a damaged device(s) that falls outside of warranty repair, or your devices(s) are out of their warranty period. There are repair costs included in the document on the final page.',
    topLine: 'Y',
    updatedBy: 'Lyndon Evans',
  },
  {
    businessCritical: 'N',
    createdDate: '07/11/2018 13:37:36',
    headline: 'VAS 6154(A) Dummy news',
    id: '10',
    imageName: '6154-a.PNG',
    ipAddress: '147.161.171.80',
    lastUpdated: '12/01/2022 11:15:00',
    linkTo:
      'content/documents/VAS_Hardware_Support/VAS_6154A/VAS_6154_Order_for_Repair_with_Costs.pdf',
    newsType: 'News',
    newstext:
      'Just a test of the news page for items missing an / at the beginning',
    topLine: 'Y',
    updatedBy: 'Lyndon Evans',
  },
];
