export default odisDummyData = [
  {
    id: '1',
    software: 'ODIS',
    fullName: 'Offboard Diagnostic Information System',
    brandVersions: [
      {
        id: '1',
        softwareId: '1',
        brandCode: 'AU',
        mainFeatureVersion: '89.5.330',
        productVersion: '5.1.6',
        dataVersion: '2.19.5',
        otherVersion: '',
        updatedBy: 'Beth Clarke',
        dateCreated: '01/10/2019',
      },
      {
        id: '5',
        softwareId: '1',
        brandCode: 'CV',
        mainFeatureVersion: '89.5.290',
        productVersion: '5.1.6',
        dataVersion: '2.18.9',
        otherVersion: '',
        updatedBy: 'Beth Clarke',
        dateCreated: '01/10/2019',
      },
      {
        id: '3',
        softwareId: '1',
        brandCode: 'SE',
        mainFeatureVersion: '89.5.250',
        productVersion: '5.1.6',
        dataVersion: '2.16.6',
        otherVersion: '',
        updatedBy: 'Beth Clarke',
        dateCreated: '01/10/2019',
      },
      {
        id: '4',
        softwareId: '1',
        brandCode: 'SK',
        mainFeatureVersion: '89.5.340',
        productVersion: '5.1.6',
        dataVersion: '2.24.7',
        otherVersion: '',
        updatedBy: 'Beth Clarke',
        dateCreated: '01/10/2019',
      },
      {
        id: '2',
        softwareId: '1',
        brandCode: 'VW',
        mainFeatureVersion: '89.5.260',
        productVersion: '5.1.6',
        dataVersion: '2.39.11',
        otherVersion: '',
        updatedBy: 'Beth Clarke',
        dateCreated: '01/10/2019',
      },
    ],
  },
];
