export default serviceMeasuresDummyData = [
  {
    id: '203',
    menuText: 'STAHLWILLE Torque Wrenches',
    toolsAffected:
      'Torque Wrenches: VAG 1331 1331A,  1332 1332A, 1576 1576A, 1601, VAS 5820 VAS 5820A',
    toolBrief: 'Stahwille_Action_ANNEX_BC_010519.pdf',
    dateCreated: '09/10/2021 08:12:00',
    lastUpdated: '05/10/2021 14:26:21',
    updatedBy: 'Simon Groves',
    expiryDate: '12/10/2021',
    startDate: '09/10/2021',
    actionSteps: 'YYNNNNNY',
    actionText:
      'Please do not mark the service measure as complete until you have received all of your wrenches back from Stahlwille. Thank you',
    auTargetSites: '31',
    vwTargetSites: '18',
    seTargetSites: '10',
    skTargetSites: '9',
    cvTargetSites: '5',
    auTargetItems: '31',
    vwTargetItems: '18',
    seTargetItems: '10',
    skTargetItems: '9',
    cvTargetItems: '5',
    numItemsText: 'How many affected Stahlwille torque wrenches do yo',
    imTargetSites: '',
    imTargetItems: '',
    retailerSpecific: 'Y',
    initialQuestion: '',
    confirmationQuestion: '',
    serialNumberQuestion: '',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '472',
  },
  {
    id: '204',
    menuText: 'Towing bracket 3336',
    toolsAffected: 'Bracket 3336',
    toolBrief: 'New TIW Document Towing bracket 3336_3336A Action - ANNEX.pdf',
    dateCreated: '29/04/2019 12:27:44',
    lastUpdated: '02/09/2019 09:30:40',
    updatedBy: 'Lyndon Evans',
    expiryDate: '09/10/2021',
    startDate: '01/09/2021',
    actionSteps: 'YYNYNNNN',
    actionText:
      'Within the text box of the MRA please use ref, Service Measure 3336',
    auTargetSites: '23',
    vwTargetSites: '2',
    seTargetSites: '0',
    skTargetSites: '0',
    cvTargetSites: '0',
    auTargetItems: '23',
    vwTargetItems: '2',
    seTargetItems: '0',
    skTargetItems: '0',
    cvTargetItems: '0',
    numItemsText: '',
    imTargetSites: '',
    imTargetItems: '',
    retailerSpecific: 'Y',
    initialQuestion: '',
    confirmationQuestion: '',
    serialNumberQuestion: '',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '539',
  },
  {
    id: '212',
    menuText: 'Mounting component T10556',
    toolsAffected: 'T10556',
    toolBrief:
      'New TIW Document Mounting Component T105562 Action - ANNEX - Copy.pdf',
    dateCreated: '02/09/2019 09:14:39',
    lastUpdated: '06/09/2019 14:10:13',
    updatedBy: 'Lyndon Evans',
    expiryDate: '16/10/2021',
    startDate: '03/10/2021',
    actionSteps: 'YNYYNNNN',
    actionText: '',
    auTargetSites: '52',
    vwTargetSites: '2',
    seTargetSites: '0',
    skTargetSites: '0',
    cvTargetSites: '0',
    auTargetItems: '52',
    vwTargetItems: '2',
    seTargetItems: '0',
    skTargetItems: '0',
    cvTargetItems: '0',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'Y',
    initialQuestion: '',
    confirmationQuestion: '',
    serialNumberQuestion: '',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '35',
  },
  {
    id: '250',
    menuText: 'Electronic measuring system for camshaft adjustment ',
    toolsAffected: 'VAS 611 007',
    toolBrief: 'Service measure _VAS 611007_.pdf',
    dateCreated: '06/12/2019 15:16:00',
    lastUpdated: '12/02/2020 13:53:47',
    updatedBy: 'Lyndon Evans',
    expiryDate: '26/02/2020',
    startDate: '16/12/2019',
    actionSteps: 'YYNNYNNN',
    actionText:
      'Please mark this Service Measure as Completed ONLY WHEN you have carried out the conversion with the kit provided.',
    auTargetSites: '133',
    vwTargetSites: '235',
    seTargetSites: '139',
    skTargetSites: '150',
    cvTargetSites: '100',
    auTargetItems: '133',
    vwTargetItems: '235',
    seTargetItems: '139',
    skTargetItems: '150',
    cvTargetItems: '100',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'STEP 1.  Is the serial number of your VAS 611007 within the affected range as outlined in the adjacent service brief i.e.  lower than 02500?',
    confirmationQuestion:
      'STEP 3 Please mark this Service Measure as Completed by *** the kit provided. Then select the green button below, Confirm all actions have been completed. \r\n',
    serialNumberQuestion:
      'STEP 2.  Please provide the Serial Number for your VAS 611007 in the field below . Once we receive this, we will send a Conversion Kit to you in your parts cage. At this stage please save your progress by clicking the yellow Save Progress button below',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '382',
  },
  {
    id: '253',
    menuText:
      'T40093/5 Service Measure Part One:  part of engine support bracket',
    toolsAffected: 'T40093/5 bracket',
    toolBrief: 'Service Measure _T40093-5_2020-05_eng.pdf',
    dateCreated: '09/06/2020 11:45:58',
    lastUpdated: '16/07/2020 16:55:53',
    updatedBy: 'Lyndon Evans',
    expiryDate: '15/07/2020',
    startDate: '09/06/2020',
    actionSteps: 'NNNNNNNN',
    actionText: '',
    auTargetSites: '136',
    vwTargetSites: '220',
    seTargetSites: '140',
    skTargetSites: '152',
    cvTargetSites: '100',
    auTargetItems: '136',
    vwTargetItems: '220',
    seTargetItems: '140',
    skTargetItems: '152',
    cvTargetItems: '100',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'Do you have a affected T40093/5 as per the image and briefing details attached. i.e does your T40093/5 have an additional weld as per the image?',
    confirmationQuestion:
      'Have you completed all actions for the service measure?',
    serialNumberQuestion: 'Please provide a serial number for the item.',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '400',
  },
  {
    id: '254',
    menuText: 'R744 C02 service station VAS 581009',
    toolsAffected: 'VAS 581 009 (ASE 58100900000) ',
    toolBrief: 'LW-Sondernewsletter_VAS_581_009_eng.pdf',
    dateCreated: '02/10/2020 07:48:30',
    lastUpdated: '10/11/2020 08:18:24',
    updatedBy: 'Simon Groves',
    expiryDate: '10/10/2021',
    startDate: '02/10/2021',
    actionSteps: 'YNNNNNNN',
    actionText: '',
    auTargetSites: '8',
    vwTargetSites: '0',
    seTargetSites: '0',
    skTargetSites: '0',
    cvTargetSites: '0',
    auTargetItems: '8',
    vwTargetItems: '0',
    seTargetItems: '0',
    skTargetItems: '0',
    cvTargetItems: '0',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'Y',
    initialQuestion: 'Please confirm that you have viewed the Service Measure',
    confirmationQuestion:
      'Have you completed all actions as described in the service measure?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'C',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '8',
  },
  {
    id: '255',
    menuText: 'T40093/5 Service Measure PART TWO',
    toolsAffected: 'T40093/5 : part of engine support bracket',
    toolBrief: 'Service_Measure_T40093-5_2020_05_Part_two.pdf',
    dateCreated: '19/10/2020 11:58:48',
    lastUpdated: '02/11/2020 13:22:46',
    updatedBy: 'Simon Groves',
    expiryDate: '17/12/2020',
    startDate: '05/11/2020',
    actionSteps: 'YNNYNNNN',
    actionText: '',
    auTargetSites: '11',
    vwTargetSites: '26',
    seTargetSites: '4',
    skTargetSites: '52',
    cvTargetSites: '5',
    auTargetItems: '11',
    vwTargetItems: '26',
    seTargetItems: '4',
    skTargetItems: '52',
    cvTargetItems: '5',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'Y',
    initialQuestion:
      'As part of the Service Measure carried out earlier in 2020, your site confirmed that the affected items were present in your workshop. You have been AutoIssued the replacement parts. Please confirm when you are in receipt of the replacement items.',
    confirmationQuestion:
      'Have you completed all actions as described in the service measure  i.e. returns code type ZRU0, item category is ZH1?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '60',
  },
  {
    id: '256',
    menuText: 'Recall of adapters T40093/6 and T40150/8: Phase One',
    toolsAffected: 'T40093/6 and T40150/8',
    toolBrief: 'Service Measure Recall T40093-6 and T40150-8.pdf',
    dateCreated: '28/10/2020 12:50:45',
    lastUpdated: '29/10/2020 16:38:34',
    updatedBy: 'Beth Clarke',
    expiryDate: '13/11/2020',
    startDate: '30/10/2020',
    actionSteps: 'YYNNNNNY',
    actionText:
      'We will confirm in a 2nd phase Service Measure how we will exchange all identified items.',
    auTargetSites: '136',
    vwTargetSites: '249',
    seTargetSites: '145',
    skTargetSites: '155',
    cvTargetSites: '103',
    auTargetItems: '136',
    vwTargetItems: '249',
    seTargetItems: '145',
    skTargetItems: '155',
    cvTargetItems: '103',
    numItemsText:
      'How many affected items (T40093/6 or T40150/8) combined  do you have and/or have you sold?',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      "Are the tools T40093/6, sold as part of T40093, T40093A and T40093B or T40150/8 sold as part of T40150 in your workshop or have you sold any of them to 3rd parties? \r\nIf yes,  remove them from your workshop and clearly mark them as 'NOT FIT FOR USE'\r\n",
    confirmationQuestion:
      'Have you quarantined all of the reported affected equipment?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '362',
  },
  {
    id: '258',
    menuText: 'R744 C02 service station VAS 581009: PART TWO',
    toolsAffected: 'VAS 581009',
    toolBrief: 'LW_Sondernewsletter_VAS_581_009_eng_x.pdf',
    dateCreated: '09/11/2020 17:05:08',
    lastUpdated: '25/11/2020 14:14:08',
    updatedBy: 'Lyndon Evans',
    expiryDate: '31/12/2020',
    startDate: '09/11/2020',
    actionSteps: 'YNNNNNNN',
    actionText: '',
    auTargetSites: '7',
    vwTargetSites: '0',
    seTargetSites: '0',
    skTargetSites: '0',
    cvTargetSites: '0',
    auTargetItems: '7',
    vwTargetItems: '0',
    seTargetItems: '0',
    skTargetItems: '0',
    cvTargetItems: '0',
    numItemsText: '',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'Y',
    initialQuestion:
      'Have you read this article and registered your device with AVL DITEST?',
    confirmationQuestion:
      'Have AVL DITEST completed the repairs outlined in the Service Measure and is your device now fully serviceable?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '7',
  },
  {
    id: '259',
    menuText: 'T10254/5  PHASE ONE',
    toolsAffected: 'T10254, T10254/5, V03839037M and V03839310BD',
    toolBrief: 'T10254-5.pdf',
    dateCreated: '13/11/2020 09:02:50',
    lastUpdated: '13/11/2020 09:06:01',
    updatedBy: 'Simon Groves',
    expiryDate: '07/07/2021',
    startDate: '14/05/2021',
    actionSteps: 'YNNNNNNY',
    actionText: '',
    auTargetSites: '136',
    vwTargetSites: '249',
    seTargetSites: '145',
    skTargetSites: '155',
    cvTargetSites: '103',
    auTargetItems: '136',
    vwTargetItems: '249',
    seTargetItems: '155',
    skTargetItems: '145',
    cvTargetItems: '103',
    numItemsText:
      'How many affected items (T10254/5) do you have and/or have you sold?',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      "Is the component T10254/5 (which has been sold as part of the kits or via an individual part number T10254, T10254/5, V03839037M and V03839310BD)  in your workshop or have you sold any of them to 3rd parties? \r\nIf yes,  remove them from your workshop and clearly mark them as 'NOT FIT FOR USE'\r\n",
    confirmationQuestion:
      'Have you quarantined all of the reported affected equipment?',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '325',
  },
  {
    id: '260',
    menuText: 'T10057 Release Tool',
    toolsAffected: 'T10057 Release Tool belonging to Production Batch G10',
    toolBrief: 'T10057_2020_12_eng-2.pdf',
    dateCreated: '22/12/2020 15:49:24',
    lastUpdated: '08/01/2021 11:51:42',
    updatedBy: 'Simon Groves',
    expiryDate: '29/07/2021',
    startDate: '08/06/2021',
    actionSteps: 'YYNNNNNY',
    actionText:
      'You MUST return the faulty T10057 via returns code type ZRU0: item category is ZH1.  But only after your order for a replacement is received. This will then create a credit note for your new order.',
    auTargetSites: '130',
    vwTargetSites: '212',
    seTargetSites: '133',
    skTargetSites: '145',
    cvTargetSites: '96',
    auTargetItems: '130',
    vwTargetItems: '213',
    seTargetItems: '133',
    skTargetItems: '145',
    cvTargetItems: '96',
    numItemsText: 'Please report the number of affected items in your workshop',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'N',
    initialQuestion:
      'Please check your T10057 release tools from Production Batch G10 (images 1 and 2) delivered from March 2019 onwards. Do they belong to batch G10?',
    confirmationQuestion:
      'Please confirm you have read and understand the actions you are required to take in this Quality Measure.',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '2',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '346',
  },
  {
    id: '261',
    menuText: 'VAS 691 005/15-3: Potential coupling issue',
    toolsAffected: 'Leak testing kit VAS 691 005/15',
    toolBrief: 'VAS_691005_coupling_2021_01_eng.pdf',
    dateCreated: '08/01/2021 10:16:15',
    lastUpdated: '13/01/2021 14:57:59',
    updatedBy: 'Simon Groves',
    expiryDate: '22/08/2021',
    startDate: '11/06/2021',
    actionSteps: 'YNNNNNNY',
    actionText: '',
    auTargetSites: '132',
    vwTargetSites: '218',
    seTargetSites: '0',
    skTargetSites: '0',
    cvTargetSites: '0',
    auTargetItems: '132',
    vwTargetItems: '218',
    seTargetItems: '0',
    skTargetItems: '0',
    cvTargetItems: '0',
    numItemsText: 'How many affected items are in your workshop?',
    imTargetSites: '1',
    imTargetItems: '1',
    retailerSpecific: 'Y',
    initialQuestion:
      'Please check your VAS 691 005/15-3 connection adapter, part of the VAS 691 005/15 leak testing kit. Is the calendar week production date, stamped on side of the device, before CW 36/2020?\r\n',
    confirmationQuestion:
      'Please confirm you have read and understand the actions you are required to take in this Quality Measure.',
    serialNumberQuestion: 'Set the text of the SERIAL NUMBER question to this',
    status: 'O',
    qMeasure_id: '3',
    retailerUpdate: '',
    retailerStatus: '',
    retailerResponses: '205',
  },
];
